name             'emacs'
maintainer       'George Jones'
maintainer_email 'gmj@pobox.com'
license          'Apache 2.0'
description      'Installs and configures emacs from source'
long_description 'Installs and configures eamcs from source, per https://raw.githubusercontent.com/eludom/HOWTO/master/emacsFromSrc.org'
supports         'ubuntu'
version          '0.1.1'
